version: "3.3"
    
services:
  whoami:
    image: "traefik/whoami"
    container_name: "test-whoami"
    hostname: "test-whoami"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.entrypoints=web"
      - "traefik.http.routers.whoami.rule=Host(`${WHOAMI_SITE}`)"

networks:
  default:
    external:
      name: reverse-public
